### ISSUE TITLE
Sir, can you use Camel-Case to regulate variables please ?

### ISSUE THREAD

**Issue by Skyenought** [blueedgetechno/windows11#57] opened 2021-08-12 17:24 UTC
Sir, I am very happy to find this project, **But** I found the rules for naming variables are too confusing ！
I originally wanted to reconstruct this project to achieve the target of  having become skilled at using react, 
I couldn't read you code fluently. Because you used Javascript very flexiable, i had to canecel my plan to use Typescript

So I **sincerely** give you some advice for updating : 
 -  Can you strengthen the specification of variable names？
 -  I think you can take a few minutes to learn about **vite**, which can make the project faster
 - Although it's a little abrupt, can you use typescript to standardize the project?

I hope you can take my advice.

**Comment by Skyenought** [comment] 2021-08-12 17:54
Ok I know. I barely understand how project is implemented by react dev-tool.
But the main problem is that I am very confused about the naming of many variables.
like :
```
<Icon fafa="faChevronRight" />
```
In fact, I can't see literally what this property means.

This is my confusion for reconstructing this project.
Because I can't quickly understand the meaning of these variables.

So now I just want you to override some variables? I think you need to spare some time to solve this problem.

**Comment by blueedgetechno** [comment] 2021-08-12 19:33
@Skyenought Thank you for your advice. I agree to @Aliyss on the TS whether or not its really worth and I learned vite after setting up this project.

And about the variable you asked, It is custom component that handles the icons and their click actions. It actually wraps three types of icons (png icons, svg icons, fafa icons) in one.

I can understand why its hard for you to understand even I dont remember what I wrote after 2 days.

**Comment by Skyenought** [comment] 2021-08-13 01:15
I really hope you can improve your skills when  reconstructing the project( I really read your code in project, so I put forward this issue to ensure that the project can become **better** ! )

**Comment by blueedgetechno** [comment] 2021-08-13 05:27
I don't think one should be labelled as low skill if he/she choses to code in their convention. It's just people are not used to work in team and that can affect their way to code but doesn't mean they are any less capable.

**Comment by Aliyss** [comment] 2021-08-13 14:31
I'll just budge in for a short moment.

Mainly because this has nothing to do with skill. And the comment above is just mean.

I notice it is a solo project. So some renaming here and there may be of benefit if multiple people work on it. However I myself am capable of reading the code and understanding what is happening. At least for the parts I went over.

I would suggest closing this issue, due to not being able to tell what the issue is about:
- Camel Case
- Vite
- Typescript
- Unreadable Variables

Additionally, concerning how the issue has been opened (just generally complaining without splitting the individual topics to different issues), I'm not so sure if @Skyenought is maybe trolling or maybe doesn't use github much.

But basically they're always free to make a PR (pull request) with the changes you want.

**Comment by blueedgetechno** [comment] 2021-08-13 17:59
Thanks @Aliyss

**Closed by blueedgetechno** 2021-08-13 17:59 UTC
